In [1]:
import torch
print(torch.cuda.is_available())

True


In [2]:
!nvidia-smi

Mon Jul 14 15:21:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.76                 Driver Version: 560.76         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   53C    P8             15W /   80W |     219MiB /   6144MiB |     33%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
device ="cuda" if torch.cuda.is_available() else "cpu"

In [5]:
torch.cuda.device_count()

1

In [6]:
tensor=torch.tensor([1,2,3],device='cuda')
print(tensor,tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [8]:
tensor_on_cpu=tensor.to("cpu")
tensor_on_cpu,tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [11]:
tensor_numpy=tensor_on_cpu.numpy()
tensor_numpy,tensor_numpy.device

(array([1, 2, 3]), 'cpu')