In [ ]:
#cuda检查
import torch
print(torch.cuda.is_available())
print(torch.__version__)


True
2.7.1+cu126


In [3]:
!nvidia-smi

Wed Jul  2 16:02:11 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.76                 Driver Version: 560.76         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1660 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   50C    P8             14W /   80W |     497MiB /   6144MiB |     31%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
scalar=torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
matrix=torch.tensor([[7,8],
               [7,10]])
matrix

tensor([[ 7,  8],
        [ 7, 10]])

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
tensor=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [14]:
print(tensor.ndim)
tensor.shape

3


torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

In [18]:
 ##random tensors
random_tensor =torch.rand(3,4)
random_tensor

tensor([[0.7221, 0.7183, 0.9004, 0.5376],
        [0.7253, 0.9896, 0.7718, 0.7134],
        [0.4525, 0.7938, 0.3401, 0.4188]])

In [19]:
random_tensor.ndim

2

In [22]:
random_image_size_tensor=torch.rand(size=(3,224,224))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [23]:
torch.rand(3,4,5)

tensor([[[0.2891, 0.9488, 0.2164, 0.7774, 0.7851],
         [0.4206, 0.1761, 0.2864, 0.3176, 0.7591],
         [0.1206, 0.3762, 0.6678, 0.9532, 0.4385],
         [0.2088, 0.3133, 0.9887, 0.8868, 0.7862]],

        [[0.4754, 0.3747, 0.8950, 0.5519, 0.4484],
         [0.8171, 0.6770, 0.4780, 0.6845, 0.0152],
         [0.1201, 0.4533, 0.7737, 0.4871, 0.4132],
         [0.6123, 0.6264, 0.4248, 0.7087, 0.2213]],

        [[0.6308, 0.1607, 0.6361, 0.1714, 0.6376],
         [0.1512, 0.4446, 0.0485, 0.2639, 0.3512],
         [0.7377, 0.3412, 0.7952, 0.7430, 0.4073],
         [0.3330, 0.8759, 0.2121, 0.4004, 0.6254]]])

In [25]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
one=torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
one.dtype

torch.float32

In [31]:
torch.range(0,10)

C:\Users\Lonepyer\AppData\Local\Temp\ipykernel_14428\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
onetoten=torch.arange(start=0,end=11,step=1)
onetoten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
ten_zeors=torch.zeros_like(input=onetoten)
ten_ones=torch.ones_like(input=onetoten)
ten_zeors,ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [39]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)##是否要对此梯度进行跟踪
